### PR TITLE
Add test commit

### PR DESCRIPTION
**Pull request by BastianZim**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by BastianZim** [comment]
ping conda-forge/help-python

**Comment by BastianZim** [comment]
Test

**Review by carterbox — CHANGES_REQUESTED** [review]
Not PR author requesting changes.

**Review by carterbox — CHANGES_REQUESTED** [review]
Other person review test 2.

**Comment by BastianZim** [comment]
Author comment.

**Comment by carterbox** [comment]
Looks like the basic label adding/removing mechanism is working. Now we need to get authentication working and test with a non-member of staged-recipes user.

I was also a bit confused about why there are both `add_author_issue_comment.yml` and `add_author_pr.yml`. Do you know of a reason not to try to merge the `on` sections and also use `||`? to combine the script condition?

**Comment by BastianZim** [comment]
Great!

That's because of the context of the run.

For example, this is how they're triggered:

https://github.com/BastianZim/test-labeler/blob/ed13cb8292ad89f6132055c8cf0adb715b15e8ac/.github/workflows/add-author-pr.yml#L15

https://github.com/BastianZim/test-labeler/blob/ed13cb8292ad89f6132055c8cf0adb715b15e8ac/.github/workflows/add-author-issue_comment.yml#L12

(github.event.**issue**.user.login vs github.event.**pull_request**.user.login)

Combining this had originally failed for me because it expects the path but I didn't try `||` maybe that works. I would go for it.

**Comment by BastianZim** [comment]
ping conda-forge/help-python

**Comment by BastianZim** [comment]
Great, the tests are completely skipped – that's good news!

**Comment by BastianZim** [comment]
Author commenting.

**Comment by BastianZim** [comment]
Let's remove author.

**Comment by carterbox** [comment]
ping conda-forge/help-python-c

**Comment by carterbox** [comment]
ping conda-forge/help-python-c

**Comment by carterbox** [comment]
This ping should work now. conda-forge/help-python-c

**Comment by carterbox** [comment]
ping conda-forge/help-python

**Comment by carterbox** [comment]
ping conda-forge/help-python

**Comment by BastianZim** [comment]
Reviewing to get debug data for correct GitHub rights.

**Comment by BastianZim** [comment]
Reviewing again

**Comment by BastianZim** [comment]
@carterbox Would you mind reviewing this because I'm the author so it's not triggering. Thanks!

**Review by carterbox — CHANGES_REQUESTED** [review]
Review comment.

**Review by carterbox — COMMENTED** [review]
review comment

**Comment by carterbox** [comment]
non-review comment

**Comment by carterbox** [comment]
It should work IF we have a access token with the following permissions:

- repo / public_repo
- admin:org / read:org

BUT, if we use a personal access token (PAT), then all the bot actions use that person's credentials and so the action is logged as being done by them.

**Comment by BastianZim** [comment]
Ok, I have updated the token to include these two so we are able to test it.

For staged-recipes, we'll have to ask CF core if we can use one of the bots for this.

**Comment by carterbox** [comment]
conda-forge/help-python-c

**Comment by carterbox** [comment]
conda-forge/help-python-c

**Comment by carterbox** [comment]
conda-forge/help-python-c

**Comment by carterbox** [comment]
conda-forge/help-python-c testing when await author cannot be removed

**Comment by carterbox** [comment]
testing when await author cannot be removed

**Comment by carterbox** [comment]
testing when team is not mentioned

**Comment by carterbox** [comment]
Uh oh. Bot evaluated this as true:
```
##[debug]Expanded: (true && 'false' && contains(Array, 'Awaiting author contribution'))
```

**Comment by carterbox** [comment]
testing when team is not mentioned

**Comment by carterbox** [comment]
testing when team is not mentioned

**Comment by carterbox** [comment]
testing when team is not mentioned

**Comment by carterbox** [comment]
testing when team is not mentioned

**Comment by carterbox** [comment]
testing when team is not mentioned

**Comment by carterbox** [comment]
testing when team is not mentioned, bit should not remove awaiting author

**Comment by carterbox** [comment]
testing when team is not mentioned, bot should not remove awaiting author

**Comment by BastianZim** [comment]
ping conda-forge/help-python

**Comment by BastianZim** [comment]
No actions are being triggered at all – let's wait.

**Comment by carterbox** [comment]
You can safely @conda-forge/help-perl because no one is on that team and the mentions don't work outside of the official repository.

**Comment by BastianZim** [comment]
Ahh good to know, thanks!

**Comment by BastianZim** [comment]
@conda-forge/help-perl

**Comment by BastianZim** [comment]
Hmm now, why is this working here but not in staged-recipes.

**Review by carterbox — COMMENTED** [review]
Test comment

**Review by carterbox — COMMENTED** [review]
Review comment

**Review by carterbox — COMMENTED** [review]
This is a review by a special person.

**Review by carterbox — COMMENTED** [review]
This is a review by a special person.

**Review by carterbox — COMMENTED** [review]
This is a review by a special person.

**Review by carterbox — COMMENTED** [review]
This is a review by a special person.

**Comment by carterbox** [comment]
Note for posterity. Label must already exist else you get a 403 response?

**Review by carterbox — COMMENTED** [review]
Just because I'm untrusting, let's test this again. For fork on same repository.

**Comment by BastianZim** [comment]
Closing as this is now working

**Pull request closed without merging**
