### PR TITLE
Combine all jobs into one file using logical operators in skips

### PR DESCRIPTION
**Pull request by carterbox**
It looks like you can use logic in the `job.[some-job-name].if` handle both PR events and Issue events in the same job.

This PR combines all the 5 jobs into 1 file and removes two duplicate jobs, so the the total number of jobs is now 3.

### CODE REVIEW

**Comment by BastianZim** [comment]
Ahh I didn't know that you can add multiple jobs. I originally created separate files so that the `if` clause is evaluated right at the beginning and the action isn't even triggered for everything. It's also possible to check if the conditions are fulfilled once the action is launched but that will be expensive. Reason is that the concurrency limit for GitHub Actions is 20 across all of CF currently, so we need to make sure that the way the action is triggered is as granular as possible. 
But let's merge this and see what happens.

**Comment by carterbox** [comment]
https://github.com/carterbox/test-labeler/actions/runs/1913446519

It looks if the `if` clause causes the job to be skipped no machine is launched and it doesn't count towards the concurrency limit, so as long as the `if` clause is sufficient, then having all the jobs in the same file doesn't affect the number of jobs.

However, as mentioned in a comment, I think the `if` clause for the job that checks for mentions of "conda-forge/help-team" may be insufficient to avoid extra runs. If we can't figure out how to keep this job from running on events that don't have text to parse, then this job should go in a separate file so it is only triggered on `issue_comment`.

**Comment by BastianZim** [comment]
Ok that's great than we can keep everything there.

About the empty comment, I think we might be able to check if the comment body is `null`, as outlined [here](https://docs.github.com/en/actions/learn-github-actions/expressions#literals). But we need to add an empty trigger somewhere and go through the debug logs to see what's actually delivered as the comment body might also be something else.

Ref: https://docs.github.com/en/actions/learn-github-actions/expressions#literals

**Comment by carterbox** [comment]
I looked at the value of `console.log(${{ toJSON(github.event.issue) }});`. This is what we get before the job is launched in order to do the job skips. I looks like the actual contents of the comment which triggers the action is not available, so we cannot skip jobs when the comment contains no text. I think it's already sufficient that we have reduced the triggers to:

```
  on:
    issue_comment:
      types: [created]
    pull_request_review:
      types: [submitted]
    pull_request_review_comment:
      types: [created]
```

**Pull request merged**
