### PR TITLE
PR for testing FORK permissions

### PR DESCRIPTION
**Pull request by carterbox**
This PR is to test how forks behave with GitHub Action permissions

### CODE REVIEW

**Comment by carterbox** [comment]
@conda-forge/help-perl

**Review by carterbox — COMMENTED** [review]
Review from author (should be ignored)

**Comment by carterbox** [comment]
@BastianZim, please review this PR to see if the bot switches the labels.

**Comment by BastianZim** [comment]
Still same error 😩

**Comment by carterbox** [comment]
https://stackoverflow.com/questions/67247752/how-to-use-secret-in-pull-request-review-similar-to-pull-request-target ?

**Comment by BastianZim** [comment]
Definitely can work. In that case we can even check for team membership again.

We just need to _really_ make sure that we sanitise the input so that no malicious injection can happen. I don't see one right now but I'll double check that.

**Comment by carterbox** [comment]
@conda-forge/help-perl

**Review by BastianZim — APPROVED** [review]

**Comment by BastianZim** [comment]
Yes that's true. What I'm thinking of is that the text that we are passing to main contains code that is then parsed by our regex functions. We just need to make sure that it stays a string and then we should be fine.

Something like 

Enter malicious code -> code is passed to main -> code is inputted into regex -> code escapes regex and wreaks havoc. 

With python I'd be fairly confident that a string is treated as string but not sure about javascript as I don't know it well enough.

**Review by BastianZim — CHANGES_REQUESTED** [review]
Test

**Comment by carterbox** [comment]
@conda-forge/help-perl

**Review by carterbox — COMMENTED** [review]
This is a review

**Review by carterbox — COMMENTED** [review]
This is a review.

**Review by carterbox — COMMENTED** [review]
Review comment

**Comment by carterbox** [comment]
@BastianZim, I don't think using `workflow_run` helps us get around this authentication because it doesn't contain information about the context which triggered the previous workflow. It only tells you the name of the person who triggered it, so we can't know which issue to do the actions on. I'm now experimenting with using different triggers like issue->unlabeled.

**Comment by carterbox** [comment]
@conda-forge/help-perl

**Comment by carterbox** [comment]
@conda-forge/help-perl

**Comment by carterbox** [comment]
@conda-forge/help-perl

**Comment by carterbox** [comment]
@conda-forge/help-perl

**Comment by carterbox** [comment]
@conda-forge/help-perl

**Review by carterbox — COMMENTED** [review]
This is a review by a special person.

**Review by carterbox — COMMENTED** [review]
This is a review by a special person.

**Review by carterbox — COMMENTED** [review]
Just because I'm untrusting, let's test this again. For branch on Fork.

**Pull request closed without merging**
